name: zntk
channels:
  - defaults
dependencies:
  - altgraph=0.17
  - bcrypt=3.2.0
  - blas=1.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - cryptography=3.4.7
  - future=0.18.2
  - icu=58.2
  - intel-openmp=2020.2
  - jpeg=9b
  - libpng=1.6.37
  - macholib=1.14
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1k
  - paramiko=2.7.2
  - pefile=2019.4.18
  - pip=21.0.1
  - pycparser=2.20
  - pycryptodome=3.10.1
  - pyinstaller=3.6
  - pynacl=1.4.0
  - pyopengl=3.1.1a1
  - pyqt=5.9.2
  - pyqtgraph=0.11.0
  - python=3.7.10
  - pyyaml=5.4.1
  - qt=5.9.7
  - scipy=1.6.2
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.35.4
  - wheel=0.36.2
  - yaml=0.2.5
  - zlib=1.2.11
  - pip:
    - cycler==0.10.0
    - kiwisolver==1.3.1
    - matplotlib==3.1.3
    - opencv-python==4.5.1.48
    - pyparsing==2.4.7
    - pyserial==3.5
    - python-dateutil==2.8.1
